---
version: '2'
services:
  logstash:
    build:
      context: build/logstash
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        LOGSTASH_DOWNLOAD_URL: "${LOGSTASH_DOWNLOAD_URL}"
    image: "${VERSIONED_IMAGE}"
